-- MySQL Script generated by MySQL Workbench
-- Sat Jun 14 14:26:41 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Shopping
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Shopping` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Shopping` ;

-- -----------------------------------------------------
-- Table `Shopping`.`TB_Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping`.`TB_Countries` (
  `Index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  PRIMARY KEY (`Index`),
  UNIQUE INDEX `Index_UNIQUE` (`Index` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopping`.`TB_Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping`.`TB_Cities` (
  `Index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IDX_Country` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  UNIQUE INDEX `IDX_Country_UNIQUE` (`IDX_Country` ASC),
  PRIMARY KEY (`Index`),
  UNIQUE INDEX `Index_UNIQUE` (`Index` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopping`.`TB_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping`.`TB_Users` (
  `Index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(20) NOT NULL,
  `FirstName` VARCHAR(30) NOT NULL,
  `LastName` VARCHAR(30) NOT NULL,
  `StreetAddress` VARCHAR(50) NOT NULL,
  `ZipCode` VARCHAR(10) NOT NULL,
  `IDX_City` INT UNSIGNED NOT NULL,
  `PhoneNumber` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Index`),
  UNIQUE INDEX `Index_UNIQUE` (`Index` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `IDX_City_UNIQUE` (`IDX_City` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopping`.`TB_Companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping`.`TB_Companies` (
  `Index` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `BarcodePrefix` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Index`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopping`.`TB_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping`.`TB_Categories` (
  `Index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Index`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopping`.`TB_Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping`.`TB_Products` (
  `Index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Barcode` VARCHAR(12) NOT NULL,
  `Name` VARCHAR(30) NULL,
  `IDX_Company` INT UNSIGNED NULL,
  `IDX_Category1` INT UNSIGNED NULL,
  `IDX_Category2` INT UNSIGNED NULL,
  `IDX_Category3` INT UNSIGNED NULL,
  PRIMARY KEY (`Index`),
  INDEX `Index_idx` (`IDX_Company` ASC),
  INDEX `Index_idx1` (`IDX_Category1` ASC, `IDX_Category2` ASC, `IDX_Category3` ASC),
  UNIQUE INDEX `Index_UNIQUE` (`Index` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopping`.`TB_UserInventoryContent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping`.`TB_UserInventoryContent` (
  `Index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IDX_User` INT UNSIGNED NOT NULL,
  `IDX_Product` INT UNSIGNED NOT NULL,
  `Quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Index`),
  UNIQUE INDEX `Index_UNIQUE` (`Index` ASC),
  INDEX `Index_idx` (`IDX_User` ASC),
  INDEX `UPC_Code_idx` (`IDX_Product` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopping`.`TB_Scanners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping`.`TB_Scanners` (
  `Index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ScannerID` VARCHAR(15) NOT NULL,
  `IDX_User` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Index`),
  UNIQUE INDEX `ScannerID_UNIQUE` (`ScannerID` ASC),
  INDEX `Index_idx` (`IDX_User` ASC),
  UNIQUE INDEX `Index_UNIQUE` (`Index` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopping`.`TB_TransactionHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping`.`TB_TransactionHistory` (
  `Index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ScanerID` VARCHAR(15) NOT NULL,
  `TransactionNumber` INT UNSIGNED NOT NULL,
  `Barcode` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Index`),
  UNIQUE INDEX `Index_UNIQUE` (`Index` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopping`.`TB_Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shopping`.`TB_Accounts` (
  `Index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IDX_User` INT UNSIGNED NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Index`),
  INDEX `Index_idx` (`IDX_User` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
